### ISSUE TITLE
nob_win64_mingw.c executable name variance.

### ISSUE THREAD

**Issue by nezvers** [tsoding/musializer#119]
As my first experience with nob I tried building with Mingw64. I'm using the same version that came with Raylib installable setup.
I noticed that building stopped at compiling Raylib's `*.o`s into an `*.a` and gave this error.
```
[INFO] CMD: x86_64-w64-mingw32-ar -crs ./build/raylib/win64-mingw/libraylib.a ./build/raylib/win64-mingw/rcore.o ./build/raylib/win64-mingw/raudio.o ./build/raylib/win64-mingw/rglfw.o ./build/raylib/win64-mingw/rmodels.o ./build/raylib/win64-mingw/rshapes.o ./build/raylib/win64-mingw/rtext.o ./build/raylib/win64-mingw/rtextures.o ./build/raylib/win64-mingw/utils.o
[ERROR] Could not create child process: 2
```
After checking content of my Mingw, I saw only `x86_64-w64-mingw32-gcc-ar` being the closest name.
Replaced here: https://github.com/tsoding/musializer/blob/f106c92934172096ed6822b6b9b276410cd99a31/src_build/nob_win64_mingw.c#L135

After that everything worked.
Dunno, maybe there's a way to check it's name?

**Comment by Markos-Th09** [comment]
This was my bad and it was fixed in #99 but it wasn't been merged yet. Distribution of mingw for windows don't include all the prefixed binaries for some reason.

**Comment by nezvers** [comment]
For that PR it indeed looked like it replaced with `ar`, but where's the merge #120 ?
The bug is still there.

**Comment by Markos-Th09** [comment]
@rexim This has been fixed by #120
